Added Transfer-Encoding: chunked header
Icinga/icingaweb2-module-jira pull request #51
Opened 2020-04-30 11:51 UTC by jbahillo

Jira instances behind a reverse proxy would require
    Content-Lenght value or Transfer-Encoding set to chunked.
    
    Some more info might be found here: https://bugs.php.net/bug.php?id=79013&edit=1 despite
    the issue mentioned here is not exactly the same (thy're referring to HTTP/2.

2020-10-09 08:31 UTC, Thomas-Gelf requested changes
Thanks for your contribution! Please use Content-Length (strlen -> body), and apply it only in case there is a body

2020-10-13 11:37 UTC, jbahillo commented
Requested change performed

2020-10-13 12:00 UTC, Thomas-Gelf approved these changes
Great, thank you!

2020-10-13 12:01 UTC, Thomas-Gelf requested changes

2020-10-13 12:01 UTC, Thomas-Gelf commented on library/Jira/RestApi.php
> +
Please remove these white-space characters

2020-10-13 12:10 UTC, Thomas-Gelf commented on library/Jira/RestApi.php
> +
Don't worry, I did so

2020-10-13 12:10 UTC, merged