WIP
Icinga/icingaweb2-module-jira pull request #95
Opened 2023-02-02 08:46 UTC by raviks789

2023-02-08 09:45 UTC, verboEse reviewed
This looks promising. If I understand this correctly, this not only allows you to include "arrays" like requested in #88, but furthermore allows you to select (?) custom JIRA fields to fill with values from Icinga and make those even configurable from the configuration page in Icinga.
I found that it's not possible to define custom fields that require other key-value pairs from the templates config file. Example:
`customfield_10184 = '{ "id": "22806" }'`
isn't working.
Will this be possible with your approach? I will create a new issue otherwise.

2023-02-13 09:47 UTC, raviks789 commented
> 22806

Do you mean, you want to get the value for one custom field for example `customfield_10184` from another custom field `customfield_ 22806`?

2023-02-13 10:22 UTC, verboEse commented
I'm not sure how this is accomplished, but in WebUI I get a drop-down when trying to change the field and only the offered values are allowed for the custom field.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/controllers/FieldsController.php
> +            $this->redirectNow(Url::fromPath('jira/fields/edit', ['template' => $template, 'fieldId' => $fieldId]));
Please use form's on event instead.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +        }
Please use form's on event instead.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +        }
Please use form's on event instead.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +// Icinga Web JIRA Integration | (c) 2023 Icinga GmbH | GPLv2
Please add a new line before.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/forms/Config/FieldsConfigForm.php
> +// Icinga Web JIRA Integration | (c) 2023 Icinga GmbH | GPLv2
Please add a new line after.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/forms/Config/FieldsConfigForm.php
> +    protected $fields = [];
Add phpDoc please.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/forms/Config/FieldsConfigForm.php
> +    protected $fieldId;
Add phpDoc please.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/forms/Config/FieldsConfigForm.php
> +     */
Please add description and new lines between params.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/forms/Config/TemplatesConfigForm.php
> +    protected $templateName;
Add phpDoc please.

2023-02-15 16:20 UTC, sukhwinder33445 commented on application/forms/Config/TemplatesConfigForm.php
> +
Remove extra line.

2023-02-15 16:20 UTC, sukhwinder33445 commented on configuration.php
> +        'url' => 'templates/show'
Please indent correctly.

2023-02-15 16:20 UTC, sukhwinder33445 commented on library/Jira/MonitoringInfo.php
> +    public function getRecursiveVar($nestedVarName, &$var)
Please add phpDoc.

2023-02-15 16:20 UTC, sukhwinder33445 commented on library/Jira/MonitoringInfo.php
> +    /**
Please add function description.

2023-02-15 16:20 UTC, sukhwinder33445 commented on library/Jira/Web/Form/NewIssueForm.php
> +    protected $templatesConfig;
Add phpDoc please.

2023-02-15 16:20 UTC, sukhwinder33445 commented on library/Jira/Web/Table/JiraCustomFields.php
> +        'data-base-target' => '_next',
Please indent correctly.

2023-02-15 16:20 UTC, sukhwinder33445 commented on library/Jira/Web/Table/JiraCustomFields.php
> +    protected $templateName;
Add phpDoc please.

2023-02-15 16:20 UTC, sukhwinder33445 commented on library/Jira/Web/Table/Templates.php
> +        'data-base-target' => '_next',
Please indent correctly.

2023-02-16 08:36 UTC, sukhwinder33445 commented on application/forms/Config/FieldsConfigForm.php
> +            'label' => 'Add Field',
Please make it changeable. You are using the same button for `add` and `edit` action.

2023-02-16 08:47 UTC, sukhwinder33445 commented on application/forms/Config/FieldsConfigForm.php
> +            'label' => 'Add Field',
Please use `Save changes` as label for `edit` action.

2023-02-16 08:48 UTC, sukhwinder33445 commented on application/forms/Config/TemplatesConfigForm.php
> +class TemplatesConfigForm extends Form
Singular please.

2023-02-16 08:49 UTC, sukhwinder33445 commented on application/forms/Config/FieldsConfigForm.php
> +class FieldsConfigForm extends Form
Singular please.

2023-02-16 08:53 UTC, sukhwinder33445 commented on application/forms/Config/TemplatesConfigForm.php
> +        }
Please use setter/getter instead.
Use `Save changes` as label for edit action.

2023-02-16 08:59 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +                t('Add a Field To Issue Template'),
`Add Custom Field` is sufficient.

2023-02-16 09:26 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +        $this->addTitle($this->translate('Configure templates'));
Please remove this. Tab title is sufficient.

2023-02-16 09:27 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +        $this->addTitle(t('Add Template'));
Please use `addTitleTab()` instead.

2023-02-16 09:31 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +            Notification::success(sprintf($this->translate('Template %s has been added'), $form->getValue('template')));
Please use `t()` instead, since you already use it above.

2023-02-16 09:32 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +        $this->addTitleTab($this->translate('Add Template'));
Remove it please.

2023-02-16 09:35 UTC, sukhwinder33445 commented on application/controllers/FieldsController.php
> +        $this->addTitle(t('Add Custom Field To Issue Template'));
Please use `addTitleTab()` and change the label to `Add Custom Field`.

2023-02-16 09:36 UTC, sukhwinder33445 commented on application/controllers/FieldsController.php
> +            Notification::success($this->translate('The custom fields have been updated'));
Use `t()` please.

2023-02-16 09:37 UTC, sukhwinder33445 commented on application/controllers/FieldsController.php
> +        $this->addTitleTab($this->translate('Add Custom Field'));
Remove this please.

2023-02-16 09:38 UTC, sukhwinder33445 commented on application/controllers/FieldsController.php
> +        $this->addTitle(t('Edit Custom Field'));
Use `addTitleTab()` please.

2023-02-16 09:38 UTC, sukhwinder33445 commented on application/controllers/FieldsController.php
> +        $this->addTitleTab($this->translate('Edit Custom Field'));
Remove this please.

2023-02-16 09:42 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +        $this->addTitle(t('Edit Template'));
Please use `addTitleTab()` instead.

2023-02-16 09:42 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +        $this->addTitleTab($this->translate('Edit Template'));
Remove this please.

2023-02-16 09:50 UTC, sukhwinder33445 reviewed
Please add the following changes:

- Fields/TemplatesController: Remove the `trash` icon from list view and add it in `editAction`.
- Change table into a list.
- Please translate all submit button labels.

2023-02-16 09:50 UTC, sukhwinder33445 commented on application/controllers/TemplatesController.php
> +            Notification::success($this->translate('The custom fields have been updated'));
Please use `t()`.

2023-02-24 09:54 UTC, sukhwinder33445 requested changes

2023-02-24 09:54 UTC, sukhwinder33445 commented on application/forms/Config/ConfigForm.php
> +        ])->addElement('password', 'password', [
Please match the indentation as above.

2023-02-24 09:54 UTC, sukhwinder33445 commented on application/forms/Config/ConfigForm.php
> +            'label'       => $this->translate('URL'),
Please fix indentation.

2023-02-24 09:54 UTC, sukhwinder33445 commented on application/forms/Config/ConfigForm.php
> +            'label' => $this->translate('Icinga Web Link'),
Please fix indentation.

2023-02-24 09:54 UTC, sukhwinder33445 commented on application/forms/Config/FieldConfigForm.php
> +            $this->getElement('fields')->setValue($this->selectedField)->addAttributes(['disabled' => true]);
Please split into multiple lines.

2023-02-24 09:54 UTC, sukhwinder33445 commented on application/forms/Config/FieldConfigForm.php
> +                'formnovalidate' => true
Fix indentation please.

2023-02-24 09:54 UTC, sukhwinder33445 commented on library/Jira/Web/Form/NewIssueForm.php
> +            'class'    => 'autosubmit'
Please fix indentation.

2023-02-24 09:54 UTC, sukhwinder33445 commented on library/Jira/Web/Table/JiraCustomFields.php
> +
Please add the license header.

2023-02-24 09:54 UTC, sukhwinder33445 commented on library/Jira/Web/Table/JiraCustomFields.php
> +                        Url::fromPath('jira/fields/edit', ['template' => $this->templateName, 'fieldId' => $field])
Please split into multiple lines.

2023-02-24 10:33 UTC, raviks789 commented on application/controllers/ConfigurationController.php
> +                $config::fromArray($form->getValues())->saveIni($config->getConfigFile());
This is required because initially if `config.ini` file is not present `->saveIni()` throws an error.

2023-02-24 13:48 UTC, sukhwinder33445 commented on application/forms/Config/ConfigForm.php
> +                'description' => $this->translate(
Fix indentation please.

2023-02-24 13:48 UTC, sukhwinder33445 commented on application/forms/Config/ConfigForm.php
> +                'label'       => $this->translate('URL'),
Fix indentation please.

2023-02-24 13:48 UTC, sukhwinder33445 commented on application/forms/Config/TemplateConfigForm.php
> +    protected $templateName;
Remove empty line please.

2023-03-06 12:32 UTC, sukhwinder33445 reviewed
Please add CSRF Token element to all forms.

2023-03-06 12:32 UTC, sukhwinder33445 commented on library/Jira/MonitoringInfo.php
> +     * @return mixed
Please add an empty line before.

2023-03-06 12:32 UTC, sukhwinder33445 commented on library/Jira/RestApi.php
> +     * @throws \Icinga\Exception\NotFoundError
Please add a new line before.

2023-03-06 12:35 UTC, sukhwinder33445 commented
There is a strange gap between the `Delete` and `Submit` buttons.

<img width="661" alt="Screenshot 2023-03-06 at 11 07 20" src="https://user-images.githubusercontent.com/54990055/223111848-e3c6750b-6fab-411b-a8ca-949c0f52e946.png">

2023-03-06 12:47 UTC, sukhwinder33445 commented on application/forms/Config/ConfigForm.php
> +                'value'         => 'cloud',
You cannot set `cloud` as default.

2023-03-07 11:01 UTC, nilmerg requested changes

2023-03-08 11:09 UTC, nilmerg approved these changes

2023-03-08 13:19 UTC, raviks789 commented
> This looks promising. If I understand this correctly, this not only allows you to include "arrays" like requested in #88, but furthermore allows you to select (?) custom JIRA fields to fill with values from Icinga and make those even configurable from the configuration page in Icinga. I found that it's not possible to define custom fields that require other key-value pairs from the templates config file. Example: `customfield_10184 = '{ "id": "22806" }'` isn't working. Will this be possible with your approach? I will create a new issue otherwise.
> 
> Update: I just found that this occurs when the custom field type is "option" - which you excluded here, probably because the assignment of "free" values from data fields in Icinga possibly won't match these possible values. Some installations _do_ have such fields configured as required though, so it would be great to include them, too. Maybe it's possible to just add a warning about this problem when configuring the field?

@verboEse, currently only string, number or array (only labels) type custom fields are supported for configuration in the Web GUI. 
In your case, which might be single-select custom field. You could directly configure it in `templates.ini` file like below.
```
[template_name]
customfield_10184.id =  "22806"
customfield_10185.value =  "option_value"
```

Or in case of multi-select custom field:
```
[template_name]
customfield_10184.0.id =  "22806"
customfield_10184.1.id =  "22807"
customfield_10185.0.value =  "option1_value"
customfield_10185.1.value =  "option2_value"
```

2023-03-08 14:08 UTC, sukhwinder33445 approved these changes

2023-03-09 15:32 UTC, merged