Release version 1.3.0
Icinga/icingaweb2-module-jira pull request #98
Opened 2023-03-07 14:43 UTC by raviks789

2023-03-07 15:17 UTC, nilmerg commented on module.info
> +Depends: monitoring (>=2.9.0), icingadb (>= 1.0.0), ipl (>=0.11.0)
please use the new `Requires` syntax like [here](https://github.com/Icinga/icingaweb2-module-cube/blob/master/module.info)

2023-03-07 15:43 UTC, lippserd requested changes
Please use dark mode for screenshots and decide for proper dimensions, i.e. 1024x768. If you're using Chrome, use [this](https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm). Then use the Chrome console commands to capture the screenshot.

2023-03-08 15:06 UTC, nilmerg requested changes

2023-03-08 15:06 UTC, nilmerg commented on doc/03-Configuration.md
> +fields. Additional jira custom fields for the issues can either be configured in Web GUI or manually:
`Jira`, uppercase first letter

2023-03-08 15:06 UTC, nilmerg commented on doc/03-Configuration.md
> +   * Once Jira module has been enabled and its settings are configured. Go to `Templates Configuratioin`
*the* Jira module

2023-03-08 15:06 UTC, nilmerg commented on doc/03-Configuration.md
> +   * Once Jira module has been enabled and its settings are configured. Go to `Templates Configuratioin`
~~configured. Go to~~
configured, visit the

2023-03-08 15:06 UTC, nilmerg commented on doc/03-Configuration.md
> +   * Once Jira module has been enabled and its settings are configured. Go to `Templates Configuratioin`
*Configuratio~~i~~n*

2023-03-08 15:06 UTC, nilmerg commented on doc/03-Configuration.md
> +   fields can be associated with host group, service group or the custom variable. They could also be some other
*a* host group, service group or ~~the~~ custom variable

2023-03-08 15:06 UTC, nilmerg commented on doc/03-Configuration.md
> +subsequently be used while creating the issue.
~~could subsequently~~
can then

2023-03-08 15:06 UTC, nilmerg commented on doc/20-Issue-History.md
> +Monitoring / Icingadb module hook
```suggestion
Monitoring module / Icinga DB Web integration
```

2023-03-14 16:38 UTC, nilmerg requested changes
* Not all screenshots are 1024px wide, e.g. the hook previews
* Some screenshots are only correctly aligned on Github, may look different on the website
  ![Screenshot from 2023-03-14 17-34-29](https://user-images.githubusercontent.com/16668527/225075003-87f2a010-03e9-4e08-9b47-77a555a34cec.png)

2023-03-14 16:38 UTC, nilmerg commented on doc/03-Configuration.md
> +Jira allows you to configure the settings in Web GUI. Once `jira` module has been enabled, go to `Configuration`
*the* .. module

2023-03-14 16:38 UTC, nilmerg commented on doc/03-Configuration.md
> +   fields can be associated with host group, service group or custom variable. They could also be some other
**a** host group, ...

2023-03-14 16:38 UTC, nilmerg commented on doc/03-Configuration.md
> +   supported in Web GUI. Multi-select array type and other type custom fields are not supported.</br>
Please avoid `<br>`

2023-03-15 16:28 UTC, lippserd approved these changes

2023-03-28 07:52 UTC, nilmerg approved these changes

2023-03-29 07:27 UTC, merged